### ISSUE TITLE
Error in simulate_mrst_case for firstJutulExample.m

### ISSUE THREAD

**Issue by nikolai-andrianov** [sintefmath/JutulDarcy.jl#38]
Hello,

I encountered the following assertion error when trying to run firstJutulExample.m from MRST 2023b distribution:

julia> simulate_mrst_case("C:/Matlab/mrst-2023b/output/jutul/qfs_wo.mat", write_mrst = true);
MRST model: Reading input file C:/Matlab/mrst-2023b/output/jutul/qfs_wo.mat.
[ Info: This is the first call to simulate_mrst_case. Compilation may take some time...
ERROR: AssertionError: size(C_f) == (dim, nf)

The reason for the error is that in TwoPointFiniteVolumeGeometry (meshes.jl:62) size(C_f) == (2, 4900) but (dim, nf) == (3, 4900).

There was a warning message during project compilation, maybe it is related to the error:

  4 dependencies had output during precompilation:
┌ OffsetArrays → OffsetArraysAdaptExt
│  WARNING: failed to initialize stack walk info
└
┌ StaticArrays → StaticArraysStatisticsExt
│  WARNING: failed to initialize stack walk info
└
┌ Compat
│  WARNING: failed to initialize stack walk info
└
┌ ILUZero
│  WARNING: failed to initialize stack walk info

Best regards,
Nikolai

**Comment by moyner** [comment]
Thanks for the report! I think I found the issue. It will be fixed in the forthcoming release of MRST. In the mean time, the patch is here: https://bitbucket.org/mrst/mrst-model-io/commits/1ae0f1b77b2cb25f987f9cd428e2402d68f37d32

A (somewhat curious) workaround is to enable gravity in MRST before export so that the case will contain the original geometry information.

**Comment by moyner** [comment]
Fixed by the latest MRST release, I think.
