### ISSUE TITLE
Support for Julia 1.7 and 1.8

### ISSUE THREAD

**Issue by gbruer15** [sintefmath/JutulDarcy.jl#50]
I've been using JutulDarcy v0.2.7 for a while, and I'm just now getting around to upgrading. It seems that v0.2.8 dropped support for Julia 1.8.5. Was that intended?

v0.2.8 adds `DelimitedFiles = "1.9.1"` to the compat section in Project.toml. But Project.toml still says `julia = "1.7"`.

**Comment by moyner** [comment]
I do not think it was intentional, but maybe DelimitedFiles or some other dependency limits the version? JutulDarcy currently uses PkgExtensions for a lot of features and that is only available in Julia 1.9. I think Julia 1.10 will be the new LTS release fairly soon, and I hope to keep that under testing in the future.

**Comment by gbruer15** [comment]
I checked on the DelimitedFiles version updates. Since Julia 1.6.0, the only interface change has been to set the `mmap` option to false. Are you fine with me making a PR to decrease the compatibility version for DelimitedFiles?
